### ISSUE TITLE
JMP long/[addr] missing several cells

### ISSUE THREAD

**Issue by jeffythedragonslayer** [undisbeliever/snesdev-notes#11]
`JMP long` and `JMP [addr]` are missing addressing mode, opcode, bytes, and cycles (extra?).

**Comment by InsaneFirebat** [comment]
JMP long is actually JML, but some assemblers will convert it for you. It has no unique opcode. Same for JMP [addr], but I'm not sure if any assemblers would accept it.

**Comment by jeffythedragonslayer** [comment]
That's interesting.  On the table on page 459 of Eyes & Lichty (the JMP page,)

`JML long`

appears as an alternate syntax for

`JMP long`

Similarly,

`JML [addr]`

appears as an alternate syntax for

`JMP [addr]`

so undisbeliever has simply listed them in a different order.  The table on page 459 of the book has the addressing mode listed in the first column.  The cells for the "Absolute Long" and "Absolute Indirect Long" rows are taller than the others and contain a lot of empty space, also the alternate syntaxes are put in parentheses and introduced with "or" so it is clear that they do not have unique opcodes.

In this HTML table, all the cells appear to have the same height, and many cells are clearly empty, so it looks like the opcode, bytes, and cycles are missing.  I suggest putting a ditto mark (") in these cells.

**Comment by undisbeliever** [comment]
I have added `rowspan`s to the Jump instructions table to eliminate the empty cells.

Please let me know if this improves the readability of the table.

**Comment by jeffythedragonslayer** [comment]
Yeah, I think that's even better than ditto marks actually.
