### ISSUE TITLE
WDM uses immediate addressing

### ISSUE THREAD

**Issue by jeffythedragonslayer** [undisbeliever/snesdev-notes#13]
In Eyes & Lichty, the addressing mode cell for WDM on page 523 is completely blank.

In http://www.6502.org/tutorials/65c816opcodes.html#6.7, it is considered immediate addressing because the byte following the 42h opcode is treated as ignored data.

Neil Parker has written about 6502 decoding here:

https://llx.com/Neil/a2/opcodes.html

Juxtaposing the full 8-bit binary opcode with the bit pattern by, we have:

```
01000010
aaabbbcc
```
Thus it is a Group Two (cc=10) instruction according to the MC6500 Microcomputer Family Programming Manual, with immediate (bbb=000) addressing mode.

**Comment by undisbeliever** [comment]
I have no idea why I wrote *Implied* for the WDM addressing mode.

I have decided to blank the addressing mode.  *Programming the 65816* by David Eyes and Ron Lichty mentions WDM is reserved for future two-byte opcodes, which implies WDM was never intended to have an addressing mode.

I looked at a few assemblers and debuggers to see what they do with WDM.  As there appears to be different syntaxes I have decided to include both on them in the WDM table.
 * ca65: `wdm 1`
 * bass: `wdm #1`
 * 64tas: `wdm #1`
 * Mesen-S debugger: `wdm #1`
 * bsnes-plus debugger: `wdm #1`

**Comment by jeffythedragonslayer** [comment]
You had it right before.

This issue was opened when I was really struggling with the hurried reading habits beaten into me by "fast paced" industry,
which of course only caused me to make more mistakes.  I am getting better, but slowly.
You guys will just have to put up with me until I'm better.

The official 65c816 datasheet, on page 31 has an "i" for "implied addressing" in the cell for WDM.
It definitely does not stand for "immediate" because a pound "#" is used for immediate in that same table.

https://www.westerndesigncenter.com/wdc/documentation/w65c816s.pdf

That would be implied type 3 to be precise if you want to add that to your opcodes page (see page 398 of Eyes & Lichty) because the mnemonic specifies no operation; no data involved.

You can come to this conclusion another way - let's say all 256 reserved opcodes got implemented.  What would their addressing mode be?
It can't be immediate because we already used up the two bytes, so no operand can follow.

In that Parker decoding article, bbb=000 is actually (zero page, X).  The only way that thinking of WDM as being immediate makes sense is if the signature byte is data that actually does something, which it doesn't.

So, there's the answer, and apologies for my scattered thinking.  At least we know why it's "implied" now.
