### ISSUE TITLE
transferring an 8-bit index register to a 16-bit accumulator typo

### ISSUE THREAD

**Issue by jeffythedragonslayer** [undisbeliever/snesdev-notes#15]
Under Transfer Registers (Index to Accumulator), I think this bullet point:

> 16 bit A (m=0): 16 bits transferred (when x=0, the high byte is 0)

should say this in parens:

> (when x=1, the high byte transferred is zeroed because XH/YH was being forced to zero)

**Comment by undisbeliever** [comment]
Thank-you for reporting this typo.

I have decided to not mention the XH/YH state in order to keep the text brief and to the point.
