### ISSUE TITLE
Postive/Negative vs. Previous/Next Block Move direction

### ISSUE THREAD

**Issue by jeffythedragonslayer** [undisbeliever/snesdev-notes#16]
The "P" and "N" suffixes in MVP and MVN stand for "Positive" and "Negative" according to https://www.westerndesigncenter.com/wdc/documentation/w65c816s.pdf, not "Previous" and "Next." They tell you the direction the address of the byte currently being copied increments/decrements in.

Also, the polarity of the "+ 1"'s and "- 1"'s in the psuedocode for both index register assignments for both opcodes are mixed up according to the official datasheet.

**Comment by undisbeliever** [comment]
I got the instruction names and +1/-1 behaviour from Chapter 18 (The Instruction Sets) of Programming the 65816 by David Eyes and Ron Lichty.

The *New 65816/65802 Instructions* table in Programming the 65816 does call `mvn` Block move negative and `mvp` Block move positive.  I should add a note to the 65816 page stating the alternative names of these instructions.

<br/>

Positive/Negative does not describe the direction of copying but rather the relationship between the source and destination addresses.  When the source and destination overlap:
 * `mvn` is used if the destination is lower (more negative) than the source
 * `mvp` is used if the destination is higher (more positive)[^1] than the source.

[^1]: Paraphrasing Table 5-7 9b. Block Move Positive, from the W65C816S pdf.

<br/>


I also double checked the +1/-1 behaviour by checking what higan does.

higan/component/processor/wdc65816/disassembler.cpp
```
  op(0x44, "mvp", move)
[...]
  op(0x54, "mvn", move)
```


higan/component/processor/wdc65816/instruction.hpp
```
  opX(0x44, BlockMove, -1)
[...]
  opX(0x54, BlockMove, +1)
```

**Comment by jeffythedragonslayer** [comment]
Ah, that means those arrows pointing straight up and straight down in the datasheet aren't describing the direction the address of the byte currently being copied is incrementing/decrementing, but the direction the block of bytes as a whole is moving.

**Comment by undisbeliever** [comment]
I've added the alternative names for the MVN and MVP instructions to my 65816 opcodes page.
