### ISSUE TITLE
TCD does not store to the direct page

### ISSUE THREAD

**Issue by jeffythedragonslayer** [undisbeliever/snesdev-notes#18]
The "name" of TCD is listed as:

> Transfer 16 bit A to DP

TCD does not transfer the value of the accumulator to a location in the direct page, but to the direct page register itself.  The direct page is a page of 256 bytes, after all.

I think it should be "DPR" or "D" not "DP" as that would literally read "Transfer 16 bit A to direct page"

**Comment by undisbeliever** [comment]
I checked the W65C816S datasheet and it lists the Direct Page Register as `D`.

I've also changed the Stack Pointer, Data Bank Register and Program Bank Register to match the W65C816S datasheet.

Thank you for bringing this to my attention.
