### ISSUE TITLE
RTS and RTL Opcode mixup

### ISSUE THREAD

**Issue by newcomb-luke** [undisbeliever/snesdev-notes#2]
On the "65816 Opcodes" page.

For the normal 6502 microprocessor opcode 0x60 is the RTS instruction. So when the 65816 came out and needed to be (mostly) backwards-compatable, it made the RTL instruction opcode 0x6b. On the "65816 Opcodes" page RTS is listed as having the opcode 0x6b and RTL is listed as having the opcode 0x60, which seems to be backwards.

I could be incorrect but I do believe it is a bug in the website.

**Comment by undisbeliever** [comment]
That is indeed a typo, good catch.

I apologise for the delay in my response. Thank you for your patience.
