### ISSUE TITLE
Missing Operation Symbol on Opcode List

### ISSUE THREAD

**Issue by colejohnson66** [undisbeliever/snesdev-notes#4]
In the 65816 opcode list, the top contains this line:

`(Addr + Index) & 0xffff00 ≠ Addr 0xffff00`

I’m assuming there’s supposed to be a logical/bitwise AND on the right half

**Comment by undisbeliever** [comment]
> I’m assuming there’s supposed to be a logical/bitwise AND on the right half

Yes, there should have been a bitwise AND on the right half of that line.

Thank you for reporting this.
