### ISSUE TITLE
[Question] not 65816 internals but machine state?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [undisbeliever/snesdev-notes#5]
Hi undisbeliever, could you please elaborate on what this sentence means?

> The psuedo-code described in this document does not describe the 65816 internals but rather the change in machine state.

**Comment by undisbeliever** [comment]
The psuedo-code on my 65816 opcodes document describes the change in machine state at the end of the instruction.  It was written to be readable and easily understandable.  It does not describe how the 65816 implements the instruction.

<br/>

A good example of this is the *Push to Stack* and *Pull from Stack* instructions.

A more accurate way of writing a 16 bit *Push to Stack* instruction is:

```
[SP]   ← R.h
SP     ← SP - 1
[SP]   ← R.l
SP     ← SP - 1
```

But it is difficult to understand.  Instead I wrote:


```
SP     ← SP - 2
[SP+2] ← R.h
[SP+1] ← R.l
```

Which is easier to understand and more useful to a 65816 programmer.  The reader can easily see memory address `SP + 2` contains the high byte and memory address `SP + 1`  contains the low byte after the instruction has been executed.

**Comment by jeffythedragonslayer** [comment]
Ok, thanks, so you mean the pseudocode tells how to determine what the 65816 state will be after an instruction runs, but not necessarily how that state was accomplished.
