### ISSUE TITLE
COP instruction missing

### ISSUE THREAD

**Issue by jeffythedragonslayer** [undisbeliever/snesdev-notes#6]
Eyes & Lichty mentions there is a COP instruction on page 255.

**Comment by undisbeliever** [comment]
The COP instruction can be found in the [Software Interrupts](https://undisbeliever.net/snesdev/65816-opcodes.html#software-interrupts) section in the 65816 Opcodes page.

**Comment by jeffythedragonslayer** [comment]
Ok I see now sections that have multiple instructions grouped together don't have the instruction mnemonic in the section header.
